### ISSUE TITLE
Can´t get "now playing" Blueprint to display

### ISSUE THREAD

**Issue by Schadenfreund** [Blueforcer/flows_blueprints#1]
At first thank you for creating the Blueprint.

I am however having the issue, that the automation is triggered (and title / artist are captured correctly).

However nothing is shown on the display neither if I choose Notification or Custom App. 

Any hint / idea what else I could try to make it work is appreciated.

**Comment by Blueforcer** [comment]
You will not get in contact with the flow creator here. This is just a automatic blueprint sync repo (see README)

You can discuss about flows in the awtrix discord server.
